iran_strike_events = [
    {
        "name": "Tehran – Khamenei Compound & Leadership",
        "lat": 35.6892,
        "lon": 51.3890,
        "date": "2026-02-28",
        "desc": "Decapitation strike – Supreme Leader Ali Khamenei and top officials killed.",
    },
    {
        "name": "Tehran – Ministry of Defence & Intelligence",
        "lat": 35.696,
        "lon": 51.410,
        "date": "2026-02-28",
        "desc": "IRGC command buildings destroyed.",
    },
    {
        "name": "Tehran – Presidential & Parchin Complex",
        "lat": 35.55,
        "lon": 51.75,
        "date": "2026-03-03",
        "desc": "Follow-up waves on political/military sites.",
    },
    {
        "name": "Isfahan – Nuclear & Military Sites",
        "lat": 32.6546,
        "lon": 51.6680,
        "date": "2026-02-28",
        "desc": "Nuclear research facilities hit.",
    },
    {
        "name": "Natanz Enrichment Facility",
        "lat": 33.726,
        "lon": 51.726,
        "date": "2026-02-28 & 2026-03-03",
        "desc": "Primary enrichment site repeatedly targeted.",
    },
    {
        "name": "Qom – Military & Leadership Sites",
        "lat": 34.64,
        "lon": 50.88,
        "date": "2026-02-28",
        "desc": "Leadership & infrastructure struck.",
    },
    {
        "name": "Kermanshah – Missile Production",
        "lat": 34.3277,
        "lon": 47.0778,
        "date": "2026-02-28",
        "desc": "Key production facilities destroyed.",
    },
    {
        "name": "Fordow Underground Nuclear Site",
        "lat": 34.88,
        "lon": 50.01,
        "date": "2026-03-04",
        "desc": "Deep underground facility struck.",
    },
    {
        "name": "Tabriz",
        "lat": 38.08,
        "lon": 46.30,
        "date": "2026-02-28",
        "desc": "Northwest military targets.",
    },
    {
        "name": "Bushehr",
        "lat": 28.92,
        "lon": 50.83,
        "date": "2026-02-28",
        "desc": "Naval & nuclear-adjacent sites.",
    },
    {
        "name": "Bandar Abbas Naval Base & Port",
        "lat": 27.18,
        "lon": 56.27,
        "date": "2026-03-05",
        "desc": "Major southern port & IRGC navy hit.",
    },
    {
        "name": "Minab – Elementary School (Civilian)",
        "lat": 27.15,
        "lon": 57.08,
        "date": "2026-02-28",
        "desc": "Tragic civilian strike – dozens of children killed.",
    },
    {
        "name": "Chabahar IRGC Navy Base",
        "lat": 25.30,
        "lon": 60.65,
        "date": "2026-03-01",
        "desc": "Port and naval facilities targeted.",
    },
    {
        "name": "Indian Ocean off Sri Lanka – US Sub Torpedo on IRIS Dena",
        "lat": 5.141522,
        "lon": 80.529599,
        "date": "2026-03-04",
        "desc": "US Navy submarine sank Iranian frigate IRIS Dena with torpedoes (~87 sailors killed). First US sub torpedo kill since WWII.",
    },
    {
        "name": "Lorestan Province – Poldokhtar Residential Areas",
        "lat": 33.15,  # Approx Poldokhtar
        "lon": 47.71,
        "date": "2026-03-05",
        "desc": "Israeli missile strikes on residential areas; at least 6 injured (part of broad-scale infrastructure attacks).",
    },
    {
        "name": "Tehran – Military Academy & Infrastructure",
        "lat": 35.6892,
        "lon": 51.3890,
        "date": "2026-03-05 & 2026-03-06",
        "desc": "Broad-scale Israeli strikes on Tehran infrastructure, including military academy (ongoing regime foundation targeting).",
    },
    {
        "name": "Pakdasht – Abbas Abad & Shenzar Industrial Zones",
        "lat": 35.48,
        "lon": 51.68,
        "date": "2026-03-05",
        "desc": "IDF evacuation warnings and strikes on defense industrial base in Tehran Province.",
    },
]

retaliation_events = [
    {
        "name": "Tel Aviv Metro Area, Israel",
        "lat": 32.0853,
        "lon": 34.7818,
        "date": "2026-02-28 & 2026-03-01",
        "desc": "Massive missile & drone barrage.",
    },
    {
        "name": "Beit Shemesh & Central Israel",
        "lat": 31.747,
        "lon": 34.988,
        "date": "2026-03-01",
        "desc": "Civilian areas hit.",
    },
    {
        "name": "Al Udeid Air Base, Qatar",
        "lat": 25.117,
        "lon": 51.315,
        "date": "2026-02-28",
        "desc": "Largest US base heavily damaged.",
    },
    {
        "name": "US 5th Fleet HQ, Bahrain",
        "lat": 26.23,
        "lon": 50.58,
        "date": "2026-02-28",
        "desc": "Direct hits on US naval headquarters.",
    },
    {
        "name": "Al Dhafra Air Base, UAE",
        "lat": 24.25,
        "lon": 54.55,
        "date": "2026-02-28",
        "desc": "US air base targeted.",
    },
    {
        "name": "US Bases, Kuwait",
        "lat": 29.3759,
        "lon": 47.9774,
        "date": "2026-03-01",
        "desc": "Camp Arifjan area struck.",
    },
    {
        "name": "US Facilities, Saudi Arabia (Riyadh area)",
        "lat": 24.7136,
        "lon": 46.6753,
        "date": "2026-03-02",
        "desc": "Embassy and military sites hit.",
    },
    {
        "name": "US Embassy Area, Dubai",
        "lat": 25.2048,
        "lon": 55.2708,
        "date": "2026-03-03",
        "desc": "Drone & missile attacks.",
    },
    {
        "name": "Haifa Port & Northern Israel",
        "lat": 32.794,
        "lon": 34.989,
        "date": "2026-03-04",
        "desc": "New wave on northern Israel.",
    },
    {
        "name": "US Positions, Baghdad Area, Iraq",
        "lat": 33.315,
        "lon": 44.366,
        "date": "2026-03-05",
        "desc": "Retaliatory strikes on US assets in Iraq.",
    },
    {
        "name": "Tel Aviv – Hybrid Drone-Missile Attack",
        "lat": 32.0853,
        "lon": 34.7818,
        "date": "2026-03-05 & 2026-03-06",
        "desc": "Fresh Iranian hybrid attack on Tel Aviv (ongoing retaliation waves).",
    },
    {
        "name": "Azerbaijan – Drone/Missile Strikes",
        "lat": 40.4093,  # Approx Baku area
        "lon": 49.8671,
        "date": "2026-03-05",
        "desc": "First Iranian strikes on Azerbaijan; airspace closed in response.",
    },
    {
        "name": "UAE – Oil Port Strike",
        "lat": 25.2048,
        "lon": 55.2708,
        "date": "2026-03-05",
        "desc": "Iranian strikes targeted oil port in UAE (part of Gulf retaliation).",
    },
]
