iran_strike_events = [
    {
        "name": "Tehran – Khamenei Compound & Leadership",
        "lat": 35.6892,
        "lon": 51.3890,
        "date": "2026-02-28",
        "desc": "Decapitation strike – Supreme Leader Ali Khamenei and top officials killed. Launch: Nevatim Air Base (Israel) / Gulf carriers.",
    },
    {
        "name": "Tehran – Ministry of Defence & Intelligence",
        "lat": 35.696,
        "lon": 51.410,
        "date": "2026-02-28",
        "desc": "IRGC command buildings destroyed. Launch: Nevatim Air Base / Al Udeid (Qatar).",
    },
    {
        "name": "Tehran – Presidential & Parchin Complex",
        "lat": 35.55,
        "lon": 51.75,
        "date": "2026-03-03",
        "desc": "Follow-up waves on political/military sites. Launch: Nevatim Air Base.",
    },
    {
        "name": "Isfahan – Nuclear & Military Sites",
        "lat": 32.6546,
        "lon": 51.6680,
        "date": "2026-02-28",
        "desc": "Nuclear research facilities hit. Launch: Nevatim Air Base / Al Udeid.",
    },
    {
        "name": "Natanz Enrichment Facility",
        "lat": 33.726,
        "lon": 51.726,
        "date": "2026-02-28 & 2026-03-03",
        "desc": "Primary enrichment site repeatedly targeted. Launch: Nevatim Air Base.",
    },
    {
        "name": "Qom – Military & Leadership Sites",
        "lat": 34.64,
        "lon": 50.88,
        "date": "2026-02-28",
        "desc": "Leadership & infrastructure struck. Launch: Nevatim Air Base.",
    },
    {
        "name": "Kermanshah – Missile Production",
        "lat": 34.3277,
        "lon": 47.0778,
        "date": "2026-02-28",
        "desc": "Key production facilities destroyed. Launch: Nevatim Air Base.",
    },
    {
        "name": "Fordow Underground Nuclear Site",
        "lat": 34.88,
        "lon": 50.01,
        "date": "2026-03-04",
        "desc": "Deep underground facility struck. Launch: Nevatim Air Base / Gulf carriers.",
    },
    {
        "name": "Tabriz Military Targets",
        "lat": 38.08,
        "lon": 46.30,
        "date": "2026-02-28",
        "desc": "Northwest military targets. Launch: Nevatim Air Base.",
    },
    {
        "name": "Bushehr Naval & Nuclear-Adjacent Sites",
        "lat": 28.92,
        "lon": 50.83,
        "date": "2026-02-28",
        "desc": "Naval & nuclear-adjacent sites. Launch: US Gulf carriers.",
    },
    {
        "name": "Bandar Abbas Naval Base & Port",
        "lat": 27.18,
        "lon": 56.27,
        "date": "2026-03-05",
        "desc": "Major southern port & IRGC navy hit. Launch: US Gulf carriers.",
    },
    {
        "name": "Minab – Elementary School (Civilian Tragedy)",
        "lat": 27.15,
        "lon": 57.08,
        "date": "2026-02-28",
        "desc": "Tragic civilian strike – dozens of children killed (adjacent to IRGC base). Launch: US Gulf carriers (under investigation).",
    },
    {
        "name": "Chabahar IRGC Navy Base",
        "lat": 25.30,
        "lon": 60.65,
        "date": "2026-03-01",
        "desc": "Port and naval facilities targeted. Launch: US Gulf carriers.",
    },
    {
        "name": "Indian Ocean off Sri Lanka – US Sub Torpedo on IRIS Dena",
        "lat": 5.141522,
        "lon": 80.529599,
        "date": "2026-03-04",
        "desc": "US Navy submarine sank Iranian frigate IRIS Dena with torpedoes (~87 sailors killed). Launch: US fast-attack submarine (Indian Ocean).",
    },
    {
        "name": "Tehran – Oil Storage Depots & Refineries (Shahran, Shahr Rey, Tondgouyan)",
        "lat": 35.6892,
        "lon": 51.3890,
        "date": "2026-03-05 to 2026-03-09",
        "desc": "Massive strikes on fuel storage, refineries, oil depots; huge fires/explosions (first major civil energy targets). Launch: Nevatim Air Base / US Gulf carriers.",
    },
    {
        "name": "Tehran – Mehrabad International Airport",
        "lat": 35.6892,
        "lon": 51.3134,
        "date": "2026-03-07 to 2026-03-08",
        "desc": "Airstrikes on runways, aircraft, infrastructure; planes burning, major damage. Launch: Nevatim Air Base.",
    },
    {
        "name": "Tehran – Military Academy, SNSC, Presidential Office & Command Sites",
        "lat": 35.6892,
        "lon": 51.3890,
        "date": "2026-03-05 to 2026-03-07",
        "desc": "Strikes on academy, SNSC headquarters, Presidential Office, Assembly of Experts building. Launch: Nevatim Air Base.",
    },
    {
        "name": "Lorestan – Poldokhtar Residential & Military Zones",
        "lat": 33.15,
        "lon": 47.71,
        "date": "2026-03-05 & 2026-03-06",
        "desc": "Missile strikes on residential/military areas; 6+ injured. Launch: Nevatim Air Base.",
    },
    {
        "name": "Pakdasht – Abbas Abad & Shenzar Defense Industrial Zones",
        "lat": 35.48,
        "lon": 51.68,
        "date": "2026-03-05",
        "desc": "Evacuation warnings followed by strikes on defense facilities. Launch: Nevatim Air Base.",
    },
]

retaliation_events = [
    {
        "name": "Tel Aviv Metro Area, Israel",
        "lat": 32.0853,
        "lon": 34.7818,
        "date": "2026-02-28 & 2026-03-01",
        "desc": "Massive missile & drone barrage. Launch: Kermanshah / Khorramabad missile sites (western Iran).",
    },
    {
        "name": "Beit Shemesh & Central Israel",
        "lat": 31.747,
        "lon": 34.988,
        "date": "2026-03-01",
        "desc": "Civilian areas hit. Launch: Kermanshah missile sites.",
    },
    {
        "name": "Al Udeid Air Base, Qatar",
        "lat": 25.117,
        "lon": 51.315,
        "date": "2026-02-28",
        "desc": "Largest US base heavily damaged. Launch: Bandar Abbas / Shiraz (southern Iran).",
    },
    {
        "name": "US 5th Fleet HQ, Bahrain",
        "lat": 26.23,
        "lon": 50.58,
        "date": "2026-02-28",
        "desc": "Direct hits on US naval headquarters. Launch: Bandar Abbas missile/naval sites.",
    },
    {
        "name": "Al Dhafra Air Base, UAE",
        "lat": 24.25,
        "lon": 54.55,
        "date": "2026-02-28",
        "desc": "US air base targeted. Launch: Bandar Abbas / Konarak (southeast Iran).",
    },
    {
        "name": "US Bases, Kuwait (Camp Arifjan)",
        "lat": 29.3759,
        "lon": 47.9774,
        "date": "2026-03-01",
        "desc": "Camp Arifjan area struck. Launch: Bandar Abbas / Shiraz.",
    },
    {
        "name": "US Facilities, Saudi Arabia (Riyadh area)",
        "lat": 24.7136,
        "lon": 46.6753,
        "date": "2026-03-02",
        "desc": "Embassy and military sites hit. Launch: Shiraz missile base.",
    },
    {
        "name": "US Embassy Area, Dubai",
        "lat": 25.2048,
        "lon": 55.2708,
        "date": "2026-03-03",
        "desc": "Drone & missile attacks. Launch: Konarak / Bandar Abbas.",
    },
    {
        "name": "Haifa Port & Northern Israel",
        "lat": 32.794,
        "lon": 34.989,
        "date": "2026-03-04",
        "desc": "New wave on northern Israel. Launch: Kermanshah missile sites.",
    },
    {
        "name": "US Positions, Baghdad Area, Iraq",
        "lat": 33.315,
        "lon": 44.366,
        "date": "2026-03-05",
        "desc": "Retaliatory strikes on US assets in Iraq. Launch: Kermanshah / western sites.",
    },
    {
        "name": "Tel Aviv & Central/Northern Israel – Ongoing Hybrid Missile/Drone Barrage",
        "lat": 32.0853,
        "lon": 34.7818,
        "date": "2026-03-05 to 2026-03-09",
        "desc": "Persistent waves of missiles/drones; intercepts but ongoing impacts. Launch: Kermanshah / Khorramabad.",
    },
    {
        "name": "Bahrain – Water Desalination Plant & US 5th Fleet Area",
        "lat": 26.23,
        "lon": 50.58,
        "date": "2026-03-07 & 2026-03-08",
        "desc": "Drone/missile strikes; desalination plant hit. Launch: Bandar Abbas naval/missile sites.",
    },
    {
        "name": "Qatar – Al Udeid & Other Sites",
        "lat": 25.117,
        "lon": 51.315,
        "date": "2026-03-06 to 2026-03-08",
        "desc": "Fresh barrages despite Gulf apology signals. Launch: Bandar Abbas / Shiraz.",
    },
    {
        "name": "Kuwait – Missile Strikes (civilian impacts)",
        "lat": 29.3759,
        "lon": 47.9774,
        "date": "2026-03-07 & 2026-03-08",
        "desc": "Missiles hit; 2+ killed, high-rise/public damage. Launch: Bandar Abbas / Shiraz.",
    },
    {
        "name": "UAE – Oil Port & Facilities",
        "lat": 25.2048,
        "lon": 55.2708,
        "date": "2026-03-05 & 2026-03-06",
        "desc": "Oil port and other sites targeted. Launch: Konarak / Bandar Abbas.",
    },
    {
        "name": "Azerbaijan – Drone/Missile Strikes",
        "lat": 40.4093,
        "lon": 49.8671,
        "date": "2026-03-05 & 2026-03-06",
        "desc": "First confirmed strikes on Azerbaijan; airspace closed. Launch: Konarak area (southeast Iran).",
    },
]
